---
title: "p8105_hw5_xz2788"
author: "Xiaoyue Zhang"
date: "11/2/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load the necessary package

```{r load_package}
library(tidyverse)
```

First read in all file names into a dataframe

```{r filename}
longidata = tibble(
  file_name = list.files(path = "./data")
)
```

Add in the data of each file to the dataframe and unnest the list

```{r file_data, message=FALSE}
longidata$file = str_c('./data/',longidata$file_name)
longidata$data = map(longidata$file, read_csv)
longidata = unnest(longidata)
```

Tidy the dataset

```{r tidy_data}
longidata$file_name = str_replace(longidata$file_name, ".csv", "")
longidata = longidata %>% 
  select(-file) %>% 
  separate(file_name, into = c("arm", "subject_id"), sep = "_") %>% 
  gather(key = week, value = observation, week_1:week_8)
longidata$week = str_replace(longidata$week, "week_", "") %>% as.numeric()
longidata$arm = str_replace(longidata$arm, "con", "control")
longidata$arm = str_replace(longidata$arm, "exp", "experimental")
```

Check the resulting dataset to make sure it's tidy

```{r check_dataset}
head(longidata)
str(longidata)
```

Make the required spaghetti plot

```{r spaghetti_plot}
longidata$arm_id = str_c(longidata$arm, '_', longidata$subject_id)
#combine the "subject_id" and "arm" to make a new variable for later plotting

longidata %>% 
  ggplot(aes(x = week, y = observation, group = arm_id, color = arm)) +
  geom_line() +
  theme_bw() +
  labs(
    title = "Observations of each subject through time",
    x = "Week",
    y = "Observation data",
    caption = "Data from the longitudinal study"
  ) +
  theme(legend.position = "bottom")
```

